eureka:
  client:
    register-with-eureka: true

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**
          filters:
            - CustomAuthorizationFilter=
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**
<<<<<<< HEAD
        - id: results
          uri: http://localhost:8074
          predicates:
            - Path=/api/result/**
        - id: candidate
          uri: http://localhost:8034
          predicates:
            - Path=/api/candidate/**
        - id: elector
          uri: http://localhost:8024
          predicates:
            - Path=/api/elector/**
=======
        - id: auth
          uri: http://localhost:8100
          predicates:
            - Path=/api/auth/**
>>>>>>> c1d69cdb5d6535470df67235a7cffafef4b17200
